### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by darkojic** [mgoricki/apex-plugin-advanced-slider#6]
Hello,

I am trying to install this plug-in in application within workspace running on APEX 5.1.2.00.9

and I received this message:

> NOT COMPATIBLE (Your export may contain calls not supported by your application version.)

**Comment by darkojic** [comment]
False alarm. There is no problem.

**Comment by mgoricki** [comment]
Hi, 

maybe the last fix that I've made was in 5.1.4.*
Glad to see that you solved it.

Br,
Marko
