### ISSUE TITLE
click on slider

### ISSUE THREAD

**Issue by dashandwerk** [mgoricki/apex-plugin-advanced-slider#8]
Hello,

i get an error while only click the slider.

**Comment by dashandwerk** [comment]
I have forgotten the erreor message

Nachricht: TypeError: o.element is undefined

**Comment by dashandwerk** [comment]
Fehlermeldung:
Nachricht: TypeError: o.element is undefined

Datei : https://127.0.0.1/dashandwerk/dashandwerk/r/105/files/plugin/6970520196143506021/v86/advanced_slider/js/jquery-ui-1.12.1.slider.min.js?v=1
Zeile: 6

**Comment by dashandwerk** [comment]
Fehlermeldung:
Nachricht: TypeError: options.element is undefined

Datei : https://127.0.0.1/dashandwerk/dashandwerk/r/105/files/plugin/6970520196143506021/v86/advanced_slider/js/jquery-ui-1.12.1.slider.js?v=1
Zeile: 569

**Comment by mgoricki** [comment]
Hi,

what's your APEX version and plugin configuration.
I see it works fine at apex.oracle.com. Can you make sam example there?

Br,
Marko

**Comment by dashandwerk** [comment]
Hi Marko,

 

found the issue.

 

I have made the values to 0.01 instead of 100 !

Values between 0 and 1 are not working so far.

 

I will divide with 100 now and it is working fine.

 

Mit freundlichem Gruß

Frank Lehmann
Geschäftsführer


dashandwerk.net
Frank Lehmann
Lindenstrasse 10a
28755 Bremen

Tel: +49 (0) 421 56507289
Mail: info@dashandwerk.net <mailto:info@dashandwerk.net> 
Web: www.dashandwerk.net <http://www.dashandwerk.net/> 
Datenschutz: https://handwerkersoftware-mieten.de/datenschutz/


Wir verstehen ihr Handwerk 

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. 
Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte 
sofort den Absender und vernichten Sie diese E-Mail. 
Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser E-Mail sowie von Teilen dieser E-Mail ist nicht 
gestattet.

P Nicht vergessen: auch an die Umwelt denken! Ein Ausdruck ist nicht immer nötig.

 

Von: Marko Gorički <notifications@github.com> 
Gesendet: Mittwoch, 1. April 2020 13:30
An: mgoricki/apex-plugin-advanced-slider <apex-plugin-advanced-slider@noreply.github.com>
Cc: dashandwerk <info@dashandwerk.net>; Author <author@noreply.github.com>
Betreff: Re: [mgoricki/apex-plugin-advanced-slider] click on slider (#8)

 

Hi,

what's your APEX version and plugin configuration.
I see it works fine at apex.oracle.com. Can you make sam example there?

Br,
Marko

**Comment by mgoricki** [comment]
Ok. I already have an open issue for decimal numbers/steps so I'll close this one.
I'll notify you when I fix it.

Br,
Marko

**Comment by dashandwerk** [comment]
Ok, thanks a lot.

 

Mit freundlichem Gruß

Frank Lehmann
Geschäftsführer


dashandwerk.net
Frank Lehmann
Lindenstrasse 10a
28755 Bremen

Tel: +49 (0) 421 56507289
Mail: info@dashandwerk.net <mailto:info@dashandwerk.net> 
Web: www.dashandwerk.net <http://www.dashandwerk.net/> 
Datenschutz: https://handwerkersoftware-mieten.de/datenschutz/


Wir verstehen ihr Handwerk 

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. 
Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte 
sofort den Absender und vernichten Sie diese E-Mail. 
Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser E-Mail sowie von Teilen dieser E-Mail ist nicht 
gestattet.

P Nicht vergessen: auch an die Umwelt denken! Ein Ausdruck ist nicht immer nötig.

 

Von: Marko Gorički <notifications@github.com> 
Gesendet: Mittwoch, 1. April 2020 13:56
An: mgoricki/apex-plugin-advanced-slider <apex-plugin-advanced-slider@noreply.github.com>
Cc: dashandwerk <info@dashandwerk.net>; Author <author@noreply.github.com>
Betreff: Re: [mgoricki/apex-plugin-advanced-slider] click on slider (#8)

 

Ok. I already have an open issue for decimal numbers/steps so I'll close this one.
I'll notify you when I fix it.

Br,
Marko
